[package]
name = "rushell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
rdev = "0.5.2"
rexpect = "0.5.0"
rustyline = "11.0.0"